# Generated by Django 5.1.5 on 2025-02-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('table', 'seat_number')},
        ),
    ]
